### ISSUE TITLE
Add support for "Prose" plugin

### ISSUE THREAD

**Issue by justinrassier** [justinrassier/postcss-elm-css-tailwind#5]
The [prose](https://github.com/tailwindlabs/tailwindcss-typography) plugin for Tailwind provides some nice opinionated ways to style blocks of text. Adding support would be super useful for anyone who may want to use it with their elm-pages static sites or something with markdown.

**Comment by matheus23** [comment]
Here's an idea as to how elm-css code should be generated for some parts of the `.prose` plugin.

This input example:
```css
.prose{
  color: #4a5568;
  max-width: 65ch;
}

.prose [class~="lead"]{
  color: #4a5568;
  font-size: 1.25em;
  line-height: 1.6;
  margin-top: 1.2em;
  margin-bottom: 1.2em;
}

.prose a{
  color: #1a202c;
  text-decoration: none;
  font-weight: 600;
}

.prose strong{
  color: #1a202c;
  font-weight: 600;
}

.prose ol{
  counter-reset: list-counter;
  margin-top: 1.25em;
  margin-bottom: 1.25em;
}

.prose ol > li{
  position: relative;
  counter-increment: list-counter;
  padding-left: 1.75em;
}
```

Should generate a function:
```elm
import Css
import Css.Style

prose : Css.Style
prose =
    Debug.todo ""
```

Adding `prose : Css.Style` to an html element should then add a generated class (something like `_61e600f9`), so that it's not a global selector.
The CSS added to the DOM should then look like this:
```css
._61e600f9{
  color: #4a5568;
  max-width: 65ch;
}

._61e600f9 [class~="lead"]{
  color: #4a5568;
  font-size: 1.25em;
  line-height: 1.6;
  margin-top: 1.2em;
  margin-bottom: 1.2em;
}

._61e600f9 a{
  color: #1a202c;
  text-decoration: none;
  font-weight: 600;
}

._61e600f9 strong{
  color: #1a202c;
  font-weight: 600;
}

._61e600f9 ol{
  counter-reset: list-counter;
  margin-top: 1.25em;
  margin-bottom: 1.25em;
}

._61e600f9 ol > li{
  position: relative;
  counter-increment: list-counter;
  padding-left: 1.75em;
}
```

I feel like this is not possible with elm-css at the moment. It would be possible to produce a 'global' stylesheet to include and a value like `prose = class "prose"`, but I'm not sure that'd be satisfying. It wouldn't play well with elm's `--optimize`, too, as it wouldn't purge the prose css, if unused.

I'm not really knowledgeable when it comes to elm-css. Let me know if I've missed something and it's actually possible!
